name: pr

on:
  pull_request:
  workflow_dispatch:

# Cancel any current or previous job from the same PR
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-all-samples:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 #v4.3
        with:
          distribution: 'temurin'
          java-version: 17
      - run: |
          for dir in */; do (cd "$dir" && ./gradlew build); done
